version: 2.1

description: >
  Use the Oxygen open source framework to run automated tests.

display:
  source_url: https://github.com/oxygenhq/oxygen-orb
  home_url: https://docs.oxygenhq.org/

executors:
  default:
    docker:
      - image: circleci/openjdk:8u181-jdk-stretch-node-browsers

commands:
  install-oxygen-cli:
    description: >
      Install Oxygen CLI.

    parameters:
      executor:
        description: executor to use for this job
        type: executor
        default: default

    steps:
      - run: echo 'export PATH=$HOME/npm/bin:$PATH' >> $BASH_ENV
      - run:
          name: Install Oxygen CLI
          command: |
            npm set prefix=/home/circleci/npm
            npm install -g oxygen-cli

  install-selenium:
    description: >
      Install Selenium Standalone Server

    parameters:
      executor:
        description: executor to use for this job
        type: executor
        default: default

      selenium-minor-version:
        description: the minor version of Selenium Standalone Server to use
        type: string
        default: "3.5"

      selenium-patch-version:
        description: the patch version of Selenium Standalone Server to use
        type: string
        default: "3.5.3"

    steps:
      - run:
          name: Install Selenium Standalone Server
          command: |
            curl -O http://selenium-release.storage.googleapis.com/<< parameters.selenium-minor-version >>/selenium-server-standalone-<< parameters.selenium-patch-version >>.jar

  start-selenium:
    description: >
      Start Selenium Standalone Server

    parameters:
      executor:
        description: executor to use for this job
        type: executor
        default: default
      
      selenium-minor-version:
        description: the minor version of Selenium Standalone Server to use
        type: string
        default: "3.5"

      selenium-patch-version:
        description: the patch version of Selenium Standalone Server to use
        type: string
        default: "3.5.3"

    steps:
      - run:
          name: Create selenium-artifacts directory
          command: mkdir selenium-artifacts

      - run:
          name: Start Selenium Standalone Server
          command: |
            java -jar selenium-server-standalone-<< parameters.selenium-patch-version >>.jar -port 4444 -timeout 320 -browserTimeout 320 -log selenium-artifacts/selenium.log
          background: true

  run-tests:
    description: >
      Run a test case or test suite with Oxygen CLI.

    parameters:
      executor:
        description: executor to use for this job
        type: executor
        default: default

      file:
        description: >
          Test case or test suite file to execute.
        type: string
        default: ''

      results:
        description: >
          Folder in which test results will be stored. Default is oxygen-test-results.
        type: string
        default: 'oxygen-test-results'

      iter:
        description: >
          Number of times (iterations) to run the test. Default is 1.
        type: integer
        default: 1

      param:
        description: >
          Parameters file (optional). If not specified an attempt will be made to load parameters from a file named same as the test script, located in the same directory, and having extension - xlsx, xls, csv, or txt.
        type: string
        default: ''

      pm:
        description: >
          Order in which to read the parameters - sequential, random, all. Default is seq. In seq and random modes test will run exact number of times specified with the iter parameter. In all mode, all available parameters will be read sequentially. This option is mutually exclusive with iter parameter.
        type: enum
        enum: ['seq', 'random', 'all']
        default: 'seq'

      browser:
        description: >
          Browser name (chrome or ie). Default is chrome.
        type: enum
        enum: ['chrome', 'ie']
        default: 'chrome'

      selenium-url:
        description: >
          Selenium hub URL (optional). If not specified an attempt will be made to use  http://localhost:4444/wd/hub.
        type: string
        default: ''

    steps:

      - run:
          name: Create test results directory
          command: mkdir <<parameters.results>>

      - run:
          name: Run test case or test suite
          command: |
            oxygen --iter=<<parameters.iter>> --pm=<<parameters.pm>> --browser=<<parameters.browser>> \
                    <<# parameters.param>> --param=<<parameters.param>> <</ parameters.param>> \
                    <<# parameters.selenium-url>> --server=<<parameters.selenium-url>> <</ parameters.selenium-url>> \
                    --rf=junit --ro=<<parameters.results>> <<parameters.file>>

      - store_test_results:
          path: <<parameters.results>>

jobs:
  install-start-run-tests:
    description: Install Oxygen, Selenium, and Mono (optional), then start server and run a test case or test suite with Oxygen CLI
    executor: default
    parameters:
      executor:
        description: executor to use for this job
        type: executor
        default: default

      selenium-minor-version:
        description: the minor version of Selenium Standalone Server to use
        type: string
        default: "3.5"

      selenium-patch-version:
        description: the patch version of Selenium Standalone Server to use
        type: string
        default: "3.5.3"

      checkout:
        description: >
          Boolean for whether or not to checkout as a first step. Default is true.
        type: boolean
        default: true

      file:
        description: >
          Test case or test suite file to execute.
        type: string
        default: ''

      results:
        description: >
          Folder in which test results will be stored. Default is oxygen-test-results.
        type: string
        default: 'oxygen-test-results'

      iter:
        description: >
          Number of times (iterations) to run the test. Default is 1.
        type: integer
        default: 1

      param:
        description: >
          Parameters file (optional). If not specified an attempt will be made to load parameters from a file named same as the test script, located in the same directory, and having extension - xlsx, xls, csv, or txt.
        type: string
        default: ''

      pm:
        description: >
          Order in which to read the parameters - sequential, random, all. Default is seq. In seq and random modes test will run exact number of times specified with the iter parameter. In all mode, all available parameters will be read sequentially. This option is mutually exclusive with iter parameter.
        type: enum
        enum: ['seq', 'random', 'all']
        default: 'seq'

      browser:
        description: >
          Browser name (chrome or ie). Default is chrome.
        type: enum
        enum: ['chrome', 'ie']
        default: 'chrome'
    steps:
      - when:
          condition: << parameters.checkout >>
          steps:
            - checkout
      - install-oxygen-cli
      - install-selenium:
          selenium-minor-version: << parameters.selenium-minor-version >>
          selenium-patch-version: << parameters.selenium-patch-version >>
      - start-selenium:
          selenium-minor-version: << parameters.selenium-minor-version >>
          selenium-patch-version: << parameters.selenium-patch-version >>
      - run-tests:
          file: << parameters.file >>
          results: << parameters.results >>
          iter: << parameters.iter >>
          param: << parameters.param >>
          pm: << parameters.pm >>
          browser: << parameters.browser >>

examples:
  build:
    description: > 
      Install the Oxygen CLI, its dependencies, Selenium Standalone Server, start the Selenium Standalone Server and run a test suite with Oxygen CLI.
    usage:
      version: 2.1
      orbs: 
        oxygen: cloudbeat/oxygen@1.0.0
      workflows:
        oxygen_install-start-run-tests:
          jobs:
            - oxygen/install-start-run-tests:
                selenium-minor-version: "3.5"
                selenium-patch-version: "3.5.3"
                file: 'tests/suite.json'
